import { Unidad } from "./articulo-solicitud";

export const unidadesData: Unidad[] = [
    {
        cluesssa: "BCSSA001152",
        cluesimb: "BCIMB000932",
        nombre: "3 DE OCTUBRE",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "AVE. EUCALIPTO NO. 1",
        latitud: "32.4600199",
        longitud: "-116.9380942",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000633",
        cluesimb: "BCIMB000512",
        nombre: "ALGODONES",
        municipio: "MEXICALI",
        localidad: "VICENTE GUERRERO (ALGODONES)",
        jurisdiccion: "MEXICALI",
        direccion: "ENTRE QUINTA Y CUARTA",
        latitud: "32.7168679",
        longitud: "-114.7325261",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000143",
        cluesimb: "BCIMB000133",
        nombre: "BAHÍA DE LOS ÁNGELES",
        municipio: "SAN QUINTIN",
        localidad: "BAHIA DE LOS ANGELES",
        jurisdiccion: "VICENTE GUERRERO",
        direccion: "CONOCIDO, BAHIA DE LOS ANGELES",
        latitud: "28.9481",
        longitud: "-113.5611",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000411",
        cluesimb: "BCIMB000331",
        nombre: "BENITO GARCÍA",
        municipio: "ENSENADA",
        localidad: "RANCHO CAÑON BUENA VISTA (EL ZORRILLO)",
        jurisdiccion: "ENSENADA",
        direccion: "CALLE OCOTLAN Y JOSE MARIA IGLESIAS MZ. 16 S/N",
        latitud: "31.672761",
        longitud: "-116.514683",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000324",
        cluesimb: "BCIMB000290",
        nombre: "BENITO JUÁREZ",
        municipio: "SAN QUINTIN",
        localidad: "COLONIA BENITO JUAREZ",
        jurisdiccion: "VICENTE GUERRERO",
        direccion: "CALLE SINALOA S/N",
        latitud: "30.8511",
        longitud: "-116.0521",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000814",
        cluesimb: "BCIMB000652",
        nombre: "BENITO JUÁREZ",
        municipio: "MEXICALI",
        localidad: "BENITO JUAREZ (EJIDO TECOLOTES)",
        jurisdiccion: "MEXICALI",
        direccion: "AV. HERMENEGILDO GALEANA S/N",
        latitud: "32.57",
        longitud: "-115.0002",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001205",
        cluesimb: "BCIMB000985",
        nombre: "CAMINO VERDE",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "PROLOGANCION XICOTECATL Y MEXICANO S/N",
        latitud: "32.4746588",
        longitud: "-116.9761128",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001135",
        cluesimb: "BCIMB000915",
        nombre: "CAÑÓN DEL PADRE",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "AV. CHOIX Y SAN BLAS 5, COL. MURUA",
        latitud: "32.5234765",
        longitud: "-116.9356023",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001041",
        cluesimb: "BCIMB000845",
        nombre: "CAÑÓN DEL SAINZ",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "AMACUZAC NO. 224 EMILIANO ZAPATA",
        latitud: "32.422201",
        longitud: "-116.960202",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA017882",
        cluesimb: "BCIMB001586",
        nombre: "CARAVANA DE LA SALUD NO. 5",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA017952",
        cluesimb: "BCIMB001615",
        nombre: "CARAVANA DE LA SALUD NO.10",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA017976",
        cluesimb: "BCIMB001632",
        nombre: "CARAVANA DE LA SALUD NO.11",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "AV. LAZARO CARDENAS Y ARTURO BERNAL",
        latitud: "32.623859",
        longitud: "-115.440302",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA017911",
        cluesimb: "BCIMB001591",
        nombre: "CARAVANA DE LA SALUD NO.30",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001794",
        cluesimb: "BCIMB001364",
        nombre: "CARAVANA DE LA SALUD NO.4",
        municipio: "ENSENADA",
        localidad: "ENSENADA",
        jurisdiccion: "ENSENADA",
        direccion: "N/A",
        latitud: "31.876347",
        longitud: "-116.620663",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA018022",
        cluesimb: "BCIMB001685",
        nombre: "CARAVANA DE SALUD 31",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BOULEVARD INSURGENTES NO. 19811, ESQUINA CAMICHIN, COL. PRADERAS DE LA MESA",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA018314",
        cluesimb: "BCIMB001743",
        nombre: "CARAVANA DE SALUD NO. 5",
        municipio: "SAN QUINTIN",
        localidad: "VICENTE GUERRERO",
        jurisdiccion: "VICENTE GUERRERO",
        direccion: "CALLE FRANCISCO DE BORJA NO. 35, COL. 13 DE MAYO",
        latitud: "30.708721",
        longitud: "-115.987797",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA017771",
        cluesimb: "BCIMB001545",
        nombre: "CARAVANA NO. 25",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA017766",
        cluesimb: "BCIMB001533",
        nombre: "CARAVANA NO. 26",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA017800",
        cluesimb: "BCIMB001562",
        nombre: "CARAVANA NO. 7",
        municipio: "SAN QUINTIN",
        localidad: "VICENTE GUERRERO",
        jurisdiccion: "VICENTE GUERRERO",
        direccion: "CALLE FRANCISCO DE BORJA NO. 35",
        latitud: "30.708721",
        longitud: "-115.987797",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA017783",
        cluesimb: "BCIMB001550",
        nombre: "CARAVANA NO. 9",
        municipio: "SAN QUINTIN",
        localidad: "VICENTE GUERRERO",
        jurisdiccion: "VICENTE GUERRERO",
        direccion: "CALLE FRANCISCO DE BORJA NO. 35",
        latitud: "30.708721",
        longitud: "-115.987797",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001695",
        cluesimb: "BCIMB001306",
        nombre: "CENTRO DE SALUD CAMALU",
        municipio: "SAN QUINTIN",
        localidad: "CAMALU",
        jurisdiccion: "VICENTE GUERRERO",
        direccion: "LIC. BENITO JUAREZ",
        latitud: "30.8368",
        longitud: "-116.0648",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA017923",
        cluesimb: "BCIMB001603",
        nombre: "CENTRO DE SALUD EJIDO PÁTZCUARO",
        municipio: "MEXICALI",
        localidad: "EJIDO PATZCUARO",
        jurisdiccion: "MEXICALI",
        direccion: "PATZCUARO Y SONORA S/N, EJIDO PATZCUARO",
        latitud: "32.348993",
        longitud: "-115.068807",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA018010",
        cluesimb: "BCIMB001673",
        nombre: "CENTRO DE SALUD TECATE",
        municipio: "TECATE",
        localidad: "TECATE",
        jurisdiccion: "TIJUANA",
        direccion: "JOSÉ ESPINOZA S/N (LOTE 16 MANZANA 13), COL. FUNDADORES",
        latitud: "32.563482",
        longitud: "-116.589384",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA018326",
        cluesimb: "BCIMB001755",
        nombre: "CENTRO DE SALUD URBANO PLAYAS DE ROSARITO",
        municipio: "PLAYAS DE ROSARITO",
        localidad: "PLAYAS DE ROSARITO",
        jurisdiccion: "TIJUANA",
        direccion: "LAS LOMAS ALTAS ESQ LA BAJADA SIN NÚMERO, COL. LOMAS DE ROSARITO",
        latitud: "32.39742",
        longitud: "-117.060862",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA018331",
        cluesimb: "BCIMB001760",
        nombre: "CENTRO DE SALUD VILLAS DEL PRADO",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "DETRAS ESTA UNA APARCELA, LA FOTO DEL GOGLE NO ESTA ACTUALIZADA APARECE UN PARQUE DONDE ESTA ACTUALMENTE EL ESTABLECIMIENTO",
        latitud: "32.40598",
        longitud: "-116.96486",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA018080",
        cluesimb: "BCIMB001714",
        nombre: "CENTRO REGIONAL DE DESARROLLO INFANTIL Y DE ESTIMULACION TEMPRANA",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "ESTA ENTRE CENTRO DE SALUD SANTORALES Y CENTRO NUEVA VIDA",
        latitud: "32.6338344",
        longitud: "-115.5607433",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNEMES"
    },
    {
        cluesssa: "BCSSA001712",
        cluesimb: "BCIMB001323",
        nombre: "CENTRO REGIONAL DE DESARROLLO INFANTIL Y ESTIMULACION TEMPRANA MOVIL",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA000551",
        cluesimb: "BCIMB000430",
        nombre: "CIPRES",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "AV.GARDENIAS Y CAOBA S/N",
        latitud: "32.573715",
        longitud: "-115.405299",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA018034",
        cluesimb: "BCIMB001690",
        nombre: "CIUDAD COAHUILA KM 57",
        municipio: "MEXICALI",
        localidad: "CIUDAD COAHUILA (KILOMETRO CINCUENTA Y SIETE)",
        jurisdiccion: "MEXICALI",
        direccion: "AVE. CUBA Y CALLE OCTAVA S/N",
        latitud: "32.189066",
        longitud: "-114.995522",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000703",
        cluesimb: "BCIMB000565",
        nombre: "CIUDAD MORELOS",
        municipio: "MEXICALI",
        localidad: "CIUDAD MORELOS (CUERVOS)",
        jurisdiccion: "MEXICALI",
        direccion: "AV. FRANCISCO ZARCO S/N, COL. CD. MORELOS",
        latitud: "32.635998",
        longitud: "-114.84337",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001671",
        cluesimb: "BCIMB001282",
        nombre: "CLINICA DE ESPECIALIDADES DENTALES EL FLORIDO",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "SE ENCUENTRA EN EL MISMO PREDIO QUE LAS UNIDADES BCSS017742 EDIFICIO ''B'' Y CLINICA DE ATENCION COVID EDIFICIO ''A''",
        latitud: "32.471906",
        longitud: "-116.848846",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000616",
        cluesimb: "BCIMB000495",
        nombre: "COL. INDUSTRIAL",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "CALLE F Y MECANICOS S/N",
        latitud: "32.651136",
        longitud: "-115.467173",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000114",
        cluesimb: "BCIMB000104",
        nombre: "COL. JALISCO",
        municipio: "ENSENADA",
        localidad: "ENSENADA",
        jurisdiccion: "ENSENADA",
        direccion: "CALLE CHAPALA S/N, COL. JALISCO",
        latitud: "31.8523901",
        longitud: "-116.5767355",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000126",
        cluesimb: "BCIMB000116",
        nombre: "COL. LOMITAS INDECO",
        municipio: "ENSENADA",
        localidad: "ENSENADA",
        jurisdiccion: "ENSENADA",
        direccion: "ESQUINA ZOCOLOW Y CASTAÑOS",
        latitud: "31.887308",
        longitud: "-116.588352",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000131",
        cluesimb: "BCIMB000121",
        nombre: "COL. OBRERA",
        municipio: "ENSENADA",
        localidad: "ENSENADA",
        jurisdiccion: "ENSENADA",
        direccion: "ESQUINA AVE. FLORESTA Y CALLE CUARTA.",
        latitud: "31.861965",
        longitud: "-116.615211",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001275",
        cluesimb: "BCIMB001055",
        nombre: "COL. RUBÍ",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. FUNDADORES Y LIBRAMIENTO SUR S/N",
        latitud: "32.4786766",
        longitud: "-117.0373777",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000266",
        cluesimb: "BCIMB000232",
        nombre: "COL. VICENTE GUERRERO",
        municipio: "SAN QUINTIN",
        localidad: "VICENTE GUERRERO",
        jurisdiccion: "VICENTE GUERRERO",
        direccion: "ESQUINA AV. VICENTE GUERRERO Y STO. DOMINGO 221",
        latitud: "30.708721",
        longitud: "-115.987797",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000061",
        cluesimb: "BCIMB000051",
        nombre: "COLONIA LOMA LINDA",
        municipio: "ENSENADA",
        localidad: "ENSENADA",
        jurisdiccion: "ENSENADA",
        direccion: "ENTRE ART. 24 Y SEGUNDA Y O RAMPA",
        latitud: "31.8823",
        longitud: "-116.6303",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000423",
        cluesimb: "BCIMB000343",
        nombre: "COLONIA NUEVA ERA",
        municipio: "SAN QUINTIN",
        localidad: "COLONIA NUEVA ERA",
        jurisdiccion: "VICENTE GUERRERO",
        direccion: "PASEO DE LAS AGUILAS SIN NUMERO",
        latitud: "30.5086267",
        longitud: "-115.9162334",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000073",
        cluesimb: "BCIMB000063",
        nombre: "COLONIA POPULAR 2",
        municipio: "ENSENADA",
        localidad: "ENSENADA",
        jurisdiccion: "ENSENADA",
        direccion: "ENTRE PRIMERA Y SEGUNDA",
        latitud: "31.891121",
        longitud: "-116.607998",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000085",
        cluesimb: "BCIMB000075",
        nombre: "COLONIA POPULAR 89",
        municipio: "ENSENADA",
        localidad: "ENSENADA",
        jurisdiccion: "ENSENADA",
        direccion: "ESQUINA GOLFO DE CALIFORNIA Y CALAFIA",
        latitud: "31.8944374",
        longitud: "-116.5739458",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000493",
        cluesimb: "BCIMB000372",
        nombre: "COMPUERTAS",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "A UN COSTADO DE LA CASETA POLICIA",
        latitud: "32.662117",
        longitud: "-115.376578",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA017964",
        cluesimb: "BCIMB001620",
        nombre: "CUMBRES",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "MONTE ELIAS Y MONTE COROPUNA M-36 L-1 CUMBRES 2DA., SECCIÓN",
        latitud: "32.487793",
        longitud: "-117.090248",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000645",
        cluesimb: "BCIMB000524",
        nombre: "DELTA",
        municipio: "MEXICALI",
        localidad: "DELTA (ESTACION DELTA)",
        jurisdiccion: "MEXICALI",
        direccion: "CALLE IGNACIO ALLENDE Y GONZALEZ ORTEGA S/N",
        latitud: "32.3561625",
        longitud: "-115.1973577",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000650",
        cluesimb: "BCIMB000536",
        nombre: "DURANGO",
        municipio: "MEXICALI",
        localidad: "EJIDO DURANGO",
        jurisdiccion: "MEXICALI",
        direccion: "ENTRE ISIDRO OLVERA Y VICENTE GUERRERO",
        latitud: "32.249817",
        longitud: "-115.256147",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001316",
        cluesimb: "BCIMB001072",
        nombre: "EJIDO OJO DE AGUA",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "EMILIANO ZAPATA SIN NUMERO",
        latitud: "32.4720748",
        longitud: "-116.7908325",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001164",
        cluesimb: "BCIMB000944",
        nombre: "EL NIÑO",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "CALLE EL NIÑO S/N",
        latitud: "32.504671",
        longitud: "-116.79313",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000225",
        cluesimb: "BCIMB000203",
        nombre: "EL ROSARÍO DE ARRIBA",
        municipio: "SAN QUINTIN",
        localidad: "EL ROSARIO DE ARRIBA",
        jurisdiccion: "VICENTE GUERRERO",
        direccion: "KM. 56 S/N, FRENTE A ESC. PRIM. FCO. I. MADERO",
        latitud: "30.060498",
        longitud: "-115.723506",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA017602",
        cluesimb: "BCIMB001434",
        nombre: "EL SAUZAL",
        municipio: "ENSENADA",
        localidad: "EL SAUZAL DE RODRIGUEZ",
        jurisdiccion: "ENSENADA",
        direccion: "AVE. CRISANTEMOS Y BUGAMBILIAS S/N",
        latitud: "31.8906529",
        longitud: "-116.6881196",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000382",
        cluesimb: "BCIMB000326",
        nombre: "EMILIANO ZAPATA",
        municipio: "SAN QUINTIN",
        localidad: "EMILIANO ZAPATA",
        jurisdiccion: "VICENTE GUERRERO",
        direccion: "CALLE 16 DE SEPTIEMBRE NO. 204",
        latitud: "30.765902",
        longitud: "-116.010411",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000160",
        cluesimb: "BCIMB000145",
        nombre: "ERÉNDIRA",
        municipio: "ENSENADA",
        localidad: "EJIDO ERENDIRA",
        jurisdiccion: "ENSENADA",
        direccion: "EMILIANO ZAPATA NO. 157",
        latitud: "31.2755",
        longitud: "-116.3753565",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA017631",
        cluesimb: "BCIMB001463",
        nombre: "ESTEBAN CANTÚ",
        municipio: "ENSENADA",
        localidad: "CORONEL ESTEBAN CANTU",
        jurisdiccion: "ENSENADA",
        direccion: "CALLE 1RA. Y C S/N, EJ. ESTEBAN CANTU",
        latitud: "31.706039",
        longitud: "-116.64255",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA017725",
        cluesimb: "BCIMB001516",
        nombre: "EX EJIDO CHAPULTEPEC",
        municipio: "ENSENADA",
        localidad: "POBLADO HEROES DE CHAPULTEPEC",
        jurisdiccion: "ENSENADA",
        direccion: "AVE. BENITO JUAREZ SIN NUMERO, COL. PRIVADA EMILIANO ZAPATA",
        latitud: "31.782227",
        longitud: "-116.59792",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA018005",
        cluesimb: "BCIMB001661",
        nombre: "EX EJIDO RUIZ CORTINES",
        municipio: "ENSENADA",
        localidad: "ENSENADA",
        jurisdiccion: "ENSENADA",
        direccion: "CALLE H Y DEL PARQUE S/N, EX-EJIDO RUIZ CORTINEZ",
        latitud: "31.896511",
        longitud: "-116.592992",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000510",
        cluesimb: "BCIMB000396",
        nombre: "FLORES MAGÓN",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "AV. AGUSTIN CASTRO Y BERNARDO REYES S/N",
        latitud: "32.6628862",
        longitud: "-115.4033032",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA017696",
        cluesimb: "BCIMB001492",
        nombre: "FLORES MAGÓN",
        municipio: "SAN QUINTIN",
        localidad: "VICENTE GUERRERO",
        jurisdiccion: "VICENTE GUERRERO",
        direccion: "AV. ING. LUIS ALZERREGA, COL. FLORES MAGON",
        latitud: "30.523799",
        longitud: "-115.943267",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001246",
        cluesimb: "BCIMB001026",
        nombre: "FLORIDO (MORITA)",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "C. ANEMONA S/N ENTRE AZAFRAN Y AVE. PRINCIPAL FRACC. EL FLORIDO 4TA. SECCIÓN",
        latitud: "32.4757522",
        longitud: "-116.8562615",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001683",
        cluesimb: "BCIMB001294",
        nombre: "FORTALECIMIENTO A LA ATENCION MEDICA NO. 06",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA000102",
        cluesimb: "BCIMB000092",
        nombre: "FRACCIONAMIENTO MAR",
        municipio: "ENSENADA",
        localidad: "ENSENADA",
        jurisdiccion: "ENSENADA",
        direccion: "ESQUINA CALLE MONTAGUE E ISLA DE CEDROS, ENTRE ISLA ANGEL DE LA GUARDA E ISLA CORONADO",
        latitud: "31.8783479",
        longitud: "-116.566314",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001280",
        cluesimb: "BCIMB001060",
        nombre: "FRANCISCO VILLA",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "MACLOVIO HERRERA 3424",
        latitud: "32.5107552",
        longitud: "-117.0556442",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000172",
        cluesimb: "BCIMB000150",
        nombre: "FRANCISCO ZARCO",
        municipio: "ENSENADA",
        localidad: "FRANCISCO ZARCO (VALLE DE GUADALUPE)",
        jurisdiccion: "ENSENADA",
        direccion: "ESQUINA CALLE 3RA. Y AVE. PRINCIPAL S/N",
        latitud: "32.0932",
        longitud: "-116.5766",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA017585",
        cluesimb: "BCIMB001410",
        nombre: "GÓMEZ MORIN",
        municipio: "ENSENADA",
        localidad: "ENSENADA",
        jurisdiccion: "ENSENADA",
        direccion: "ENRIQUE DE LA MORA S/N, COL. GOMEZ MORIN",
        latitud: "31.879974",
        longitud: "-116.544156",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000604",
        cluesimb: "BCIMB000483",
        nombre: "GONZÁLEZ ORTEGA",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "AV. RÍO NAZAS ENTRE 7MA Y 8VA S/N",
        latitud: "32.6034627",
        longitud: "-115.3911848",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000662",
        cluesimb: "BCIMB000541",
        nombre: "GUADALUPE VICTORIA",
        municipio: "MEXICALI",
        localidad: "CIUDAD GUADALUPE VICTORIA (KILOMETRO CUARENTA Y TRES)",
        jurisdiccion: "MEXICALI",
        direccion: "ENTRE NOVENA Y DECIMA",
        latitud: "32.288611",
        longitud: "-115.103287",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000505",
        cluesimb: "BCIMB000384",
        nombre: "GUAJARDO",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "ESQUINA CALLE CHILPANCINGO Y AV. COAHUILA S/N",
        latitud: "32.642085",
        longitud: "-115.5008223",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000686",
        cluesimb: "BCIMB000553",
        nombre: "HERMOSILLO",
        municipio: "MEXICALI",
        localidad: "EJIDO HERMOSILLO",
        jurisdiccion: "MEXICALI",
        direccion: "AV. BENITO JUÁREZ 128 ESQ JALISCO",
        latitud: "32.511733",
        longitud: "-114.923258",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000341",
        cluesimb: "BCIMB000302",
        nombre: "HÉROES DE LA INDEPENDENCIA",
        municipio: "ENSENADA",
        localidad: "HEROES DE LA INDEPENDENCIA (LLANO COLORADO)",
        jurisdiccion: "ENSENADA",
        direccion: "BLVD. MIGUEL HIDALGO Y COSTILLA S/N",
        latitud: "31.610915",
        longitud: "-115.890043",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001111",
        cluesimb: "BCIMB000891",
        nombre: "HERRERA",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "CITLALTEPEC 1150, COL. SANTA ROSA",
        latitud: "32.529181",
        longitud: "-117.064759",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000534",
        cluesimb: "BCIMB000413",
        nombre: "HIDALGO",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "AV.58 Y CALLE LIBERTADORES S/N",
        latitud: "32.6103206",
        longitud: "-115.4452058",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000761",
        cluesimb: "BCIMB000623",
        nombre: "HOSPITAL COMUNITARIO SAN FELIPE",
        municipio: "SAN FELIPE",
        localidad: "SAN FELIPE",
        jurisdiccion: "MEXICALI",
        direccion: "AV. MAR BERMEJO 173, AMPLIACION ZONA CENTRO",
        latitud: "31.0232256",
        longitud: "-114.839587",
        estratoUnidad: "URBANO",
        nivelAtencion: "SEGUNDO NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000015",
        cluesimb: "BCIMB000010",
        nombre: "HOSPITAL GENERAL DE ENSENADA",
        municipio: "ENSENADA",
        localidad: "ENSENADA",
        jurisdiccion: "ENSENADA",
        direccion: "CARRET.TRANSPENINSULAR KM. 111 ENSENADA -LA PAZ",
        latitud: "31.825117",
        longitud: "-116.600282",
        estratoUnidad: "URBANO",
        nivelAtencion: "SEGUNDO NIVEL",
        tipoUnidad: "HOSPITALES"
    },
    {
        cluesssa: "BCSSA000440",
        cluesimb: "BCIMB000355",
        nombre: "HOSPITAL GENERAL DE MEXICALI",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "CALLE DEL HOSPITAL S/N CENTRO CIVICO",
        latitud: "32.644334",
        longitud: "-115.476271",
        estratoUnidad: "URBANO",
        nivelAtencion: "SEGUNDO NIVEL",
        tipoUnidad: "HOSPITALES"
    },
    {
        cluesssa: "BCSSA000855",
        cluesimb: "BCIMB000676",
        nombre: "HOSPITAL GENERAL DE TECATE",
        municipio: "TECATE",
        localidad: "TECATE",
        jurisdiccion: "TIJUANA",
        direccion: "AV. 5A NO 69, COL. BENITO JUÁREZ",
        latitud: "32.557444",
        longitud: "-116.632415",
        estratoUnidad: "URBANO",
        nivelAtencion: "SEGUNDO NIVEL",
        tipoUnidad: "HOSPITALES"
    },
    {
        cluesssa: "BCSSA017590",
        cluesimb: "BCIMB001422",
        nombre: "HOSPITAL GENERAL PLAYAS DE ROSARITO",
        municipio: "PLAYAS DE ROSARITO",
        localidad: "PLAYAS DE ROSARITO",
        jurisdiccion: "TIJUANA",
        direccion: "GALILEA ESTE NO. 2200, VILLA TURISTICA, MAPAS MARCAN GALILIA ES GALILEA",
        latitud: "32.3636",
        longitud: "-117.0554",
        estratoUnidad: "URBANO",
        nivelAtencion: "SEGUNDO NIVEL",
        tipoUnidad: "HOSPITALES"
    },
    {
        cluesssa: "BCSSA000913",
        cluesimb: "BCIMB000734",
        nombre: "HOSPITAL GENERAL TIJUANA",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "AV. CENTENARIO 10851 ZONA RIO",
        latitud: "32.525583",
        longitud: "-117.009698",
        estratoUnidad: "URBANO",
        nivelAtencion: "SEGUNDO NIVEL",
        tipoUnidad: "HOSPITALES"
    },
    {
        cluesssa: "N/A",
        cluesimb: "BCIMB001796",
        nombre: "HOSPITAL GENERAL TIJUANA ZONA ESTE",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "COL, FUENTES DE MEXICALI 457, LAS FUENTE, 22245 TIJUANA, B.C.",
        latitud: "32.47195",
        longitud: "-116.84953",
        estratoUnidad: "URBANO",
        nivelAtencion: "SEGUNDO NIVEL",
        tipoUnidad: "HOSPITALES"
    },
    {
        cluesssa: "BCSSA018046",
        cluesimb: "BCIMB001702",
        nombre: "HOSPITAL MATERNO INFANTIL",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "AV. DE LA CLARIDAD S/N, COL. PLUTARCO ELIAS CALLES FRENTE UNIVERSIDAD",
        latitud: "32.6238322",
        longitud: "-115.3755598",
        estratoUnidad: "URBANO",
        nivelAtencion: "SEGUNDO NIVEL",
        tipoUnidad: "HOSPITALES"
    },
    {
        cluesssa: "BCSSA001770",
        cluesimb: "BCIMB001352",
        nombre: "HOSPITAL MATERNO INFANTIL DE TIJUANA",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "CAM. VECINAL ORIENTE #18151, RÍO TIJUANA 3A. ETAPA, RIO TIJUANA 3RA ETAPA",
        latitud: "32.489581",
        longitud: "-116.92895",
        estratoUnidad: "URBANO",
        nivelAtencion: "SEGUNDO NIVEL",
        tipoUnidad: "HOSPITALES"
    },
    {
        cluesssa: "BCSSA001094",
        cluesimb: "BCIMB000874",
        nombre: "INSURGENTES",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "MEXICANIDAD NO. 41069",
        latitud: "32.540312",
        longitud: "-116.881002",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000184",
        cluesimb: "BCIMB000162",
        nombre: "ISLA DE CEDROS",
        municipio: "ENSENADA",
        localidad: "ISLA DE CEDROS",
        jurisdiccion: "ENSENADA",
        direccion: "CARRETERA AL MORRO S/N, ISLA DE CEDROS, LITERAL UNA ISLA.",
        latitud: "28.0938",
        longitud: "-115.1935",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001263",
        cluesimb: "BCIMB001043",
        nombre: "LA JOYA",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "CALLE MEXICALI NO. 8 ESQ OJOS NEGROS, COL. TECOLOTE",
        latitud: "32.45141",
        longitud: "-116.989345",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001106",
        cluesimb: "BCIMB000886",
        nombre: "LA MESA",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "AVE. DEL CANAL S/N, DURANGO LA MESA",
        latitud: "32.495079",
        longitud: "-116.967958",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000201",
        cluesimb: "BCIMB000186",
        nombre: "LA MISIÓN",
        municipio: "ENSENADA",
        localidad: "LA MISION",
        jurisdiccion: "ENSENADA",
        direccion: "CARRETERA LIBRE ROSARITO-ENSENADA KM 56",
        latitud: "32.093387",
        longitud: "-116.851257",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001234",
        cluesimb: "BCIMB001014",
        nombre: "LA PRESA",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "KM.16 1/2 CARRET TIJUANA-TECATE ESQ LAS FLORES",
        latitud: "32.455237",
        longitud: "-116.918273",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA017684",
        cluesimb: "BCIMB001480",
        nombre: "LA PROVIDENCIA",
        municipio: "SAN QUINTIN",
        localidad: "LA PROVIDENCIA",
        jurisdiccion: "VICENTE GUERRERO",
        direccion: "EJ. LA PROVIDENCIA",
        latitud: "30.969622",
        longitud: "-116.158006",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000872",
        cluesimb: "BCIMB000693",
        nombre: "LA RUMOROSA",
        municipio: "TECATE",
        localidad: "LA RUMOROSA",
        jurisdiccion: "TIJUANA",
        direccion: "DEL AGUILA S/N, CARRET. MEXICALI-TIJUANA KM. 70",
        latitud: "32.541286",
        longitud: "-116.047287",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000546",
        cluesimb: "BCIMB000425",
        nombre: "LÁZARO CÁRDENAS",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "AV. AYUNTAMIENTO S/N",
        latitud: "32.6209859",
        longitud: "-115.4202195",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001053",
        cluesimb: "BCIMB000850",
        nombre: "LÁZARO CÁRDENAS",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "CALLE MANUEL AVILA CAMACHO ESQ. CON MANUEL M. DIEGUEZ NO. 1516",
        latitud: "32.524682",
        longitud: "-117.099874",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001176",
        cluesimb: "BCIMB000956",
        nombre: "LOMAS TAURINAS",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "LÁZARO CÁRDENAS NO. 100",
        latitud: "32.5339425",
        longitud: "-116.9896964",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA017713",
        cluesimb: "BCIMB001504",
        nombre: "LOS SANTORALES",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "CONTINENTE EUROPEO Y DEL REFUGIO S/N",
        latitud: "32.6346226",
        longitud: "-115.5616419",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000896",
        cluesimb: "BCIMB000710",
        nombre: "LUIS ECHEVERRÍA",
        municipio: "TECATE",
        localidad: "LUIS ECHEVERRIA ALVAREZ (EL HONGO)",
        jurisdiccion: "TIJUANA",
        direccion: "LOTE 2, MNZ. 98, CALLE 12 Y VENUSTIANO CARRANZA S/N",
        latitud: "32.505542",
        longitud: "-116.307203",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001613",
        cluesimb: "BCIMB001265",
        nombre: "MACLOVIO ROJAS",
        municipio: "SAN QUINTIN",
        localidad: "VICENTE GUERRERO",
        jurisdiccion: "VICENTE GUERRERO",
        direccion: "CALLE EMILIANO ZAPATA S/N",
        latitud: "30.726204",
        longitud: "-115.989164",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001193",
        cluesimb: "BCIMB000973",
        nombre: "MARÍANO MATAMOROS",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "RUTA MATAMOROS S/N",
        latitud: "32.4760856",
        longitud: "-116.881216",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000575",
        cluesimb: "BCIMB000454",
        nombre: "MEXICALI",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "BAHIA LUCERNA ENTRE AV.DEL ROSARIO",
        latitud: "32.6535058",
        longitud: "-115.5226366",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001123",
        cluesimb: "BCIMB000903",
        nombre: "MIRAMAR",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "AVE. MARIA ANTONIETA PONDS 3791",
        latitud: "32.51471",
        longitud: "-117.083005",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA017660",
        cluesimb: "BCIMB001475",
        nombre: "NAYARIT",
        municipio: "MEXICALI",
        localidad: "NAYARIT LLAMADA",
        jurisdiccion: "MEXICALI",
        direccion: "AV. LAZARO CARDENAS S/N",
        latitud: "32.3142",
        longitud: "-115.2474",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000901",
        cluesimb: "BCIMB000722",
        nombre: "NUEVA COLONIA HINDÚ",
        municipio: "TECATE",
        localidad: "NUEVA COLONIA HINDU",
        jurisdiccion: "TIJUANA",
        direccion: "SECCIÓN VIVEROS S/N, CARRET. TECATE-ENSENADA KM.-13",
        latitud: "32.49011",
        longitud: "-116.570838",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000715",
        cluesimb: "BCIMB000570",
        nombre: "NUEVO LEÓN",
        municipio: "MEXICALI",
        localidad: "NUEVO LEON",
        jurisdiccion: "MEXICALI",
        direccion: "EMILIANO ZAPATA Y LÁZARO CÁRDENAS",
        latitud: "32.4091079",
        longitud: "-115.1912281",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000580",
        cluesimb: "BCIMB000466",
        nombre: "ORIZABA",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "ENTRE BIRMANIA Y FILIPINAS",
        latitud: "32.6369926",
        longitud: "-115.5161416",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001210",
        cluesimb: "BCIMB000990",
        nombre: "PEDREGAL DE SANTA JULIA",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "OSA MENOR S/N",
        latitud: "32.487771",
        longitud: "-117.059844",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001140",
        cluesimb: "BCIMB000920",
        nombre: "PIPILA",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "LAS TORRES(C5 EN MAPAS) S/N",
        latitud: "32.505208",
        longitud: "-116.877305",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001350",
        cluesimb: "BCIMB001096",
        nombre: "PLAN LIBERTADOR",
        municipio: "PLAYAS DE ROSARITO",
        localidad: "PLAYAS DE ROSARITO",
        jurisdiccion: "TIJUANA",
        direccion: "C. BENITO JUÁREZ S/N EJ. PLAN LIBERTADOR",
        latitud: "32.4055936",
        longitud: "-117.0459362",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA017626",
        cluesimb: "BCIMB001451",
        nombre: "PORTICOS DEL MAR",
        municipio: "ENSENADA",
        localidad: "ENSENADA",
        jurisdiccion: "ENSENADA",
        direccion: "AGUSTÍN DE ITURBIDE LTE. 2, MNZ. 4, CENTRO ARTESANAL",
        latitud: "31.780929",
        longitud: "-116.58169",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001362",
        cluesimb: "BCIMB001101",
        nombre: "PRIMO TAPIA",
        municipio: "PLAYAS DE ROSARITO",
        localidad: "PRIMO TAPIA",
        jurisdiccion: "TIJUANA",
        direccion: "CALLE HIDALGO S/N PARTE BAJA EJIDO PRIMO TAPIA",
        latitud: "32.2215459",
        longitud: "-116.9171232",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000732",
        cluesimb: "BCIMB000594",
        nombre: "PROGRESO",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "ABELARDO L RODRIGUEZ (CARRETERA PROGRESO SANTA ISABEL)ENTRE LAZARO CARDENAS Y ADOLFO LOPEZ MATEO",
        latitud: "32.5826952",
        longitud: "-115.5837158",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000592",
        cluesimb: "BCIMB000471",
        nombre: "PRO-HOGAR",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "ENTRE AVENIDA EMILIANO ZAPATA Y AVENIDA VENUSTIANO CARRANZA",
        latitud: "32.644703",
        longitud: "-115.4324397",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000744",
        cluesimb: "BCIMB000606",
        nombre: "PUEBLA",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "CALLE IGNACIO ZARAGOZA S/N, CARRETERA ESTATAL NO. 2",
        latitud: "32.5718614",
        longitud: "-115.3498481",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000756",
        cluesimb: "BCIMB000611",
        nombre: "QUERÉTARO",
        municipio: "MEXICALI",
        localidad: "EJIDO HECHICERA",
        jurisdiccion: "MEXICALI",
        direccion: "AVENIDA CONSTITUYENTES DE QUERETARO (CALLE A) Y 5TA S/N, A UN LADO CASA EJIDAL",
        latitud: "32.5493139",
        longitud: "-115.1442021",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000621",
        cluesimb: "BCIMB000500",
        nombre: "REACOMODO",
        municipio: "MEXICALI",
        localidad: "COLONIA VENUSTIANO CARRANZA (LA CARRANZA)",
        jurisdiccion: "MEXICALI",
        direccion: "VDA. ARELLANO",
        latitud: "32.232315",
        longitud: "-115.167146",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000213",
        cluesimb: "BCIMB000191",
        nombre: "REAL DEL CASTILLO",
        municipio: "ENSENADA",
        localidad: "REAL DEL CASTILLO NUEVO (OJOS NEGROS)",
        jurisdiccion: "ENSENADA",
        direccion: "BLVD. LÁZARO CÁRDENAS S/N",
        latitud: "31.910308",
        longitud: "-116.26981",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001065",
        cluesimb: "BCIMB000862",
        nombre: "REFORMA",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "CALLE 7 ESQUINA GUILLERMO PRIETO NO. 22, COL. REFORMA",
        latitud: "32.466407",
        longitud: "-116.957052",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000563",
        cluesimb: "BCIMB000442",
        nombre: "RIVERA CAMPESTRE",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "ENTRE PASEO DEL ALBAHACAR Y DEL AGRACEJO",
        latitud: "32.5834905",
        longitud: "-115.430153",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000196",
        cluesimb: "BCIMB000174",
        nombre: "RODOLFO SÁNCHEZ TABOADA (MANEADERO)",
        municipio: "ENSENADA",
        localidad: "RODOLFO SANCHEZ TABOADA (MANEADERO)",
        jurisdiccion: "ENSENADA",
        direccion: "CALLE ENSENADA Y CARRET.TRANSPENINSULAR KM 20 S/N, MANEADERO",
        latitud: "31.719591",
        longitud: "-116.572713",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000230",
        cluesimb: "BCIMB000215",
        nombre: "RUBÉN JARAMILLO",
        municipio: "SAN QUINTIN",
        localidad: "EJIDO RUBEN JARAMILLO",
        jurisdiccion: "VICENTE GUERRERO",
        direccion: "MANZANA 5 LOTE 3, EJIDO RUBEN JARAMILLO",
        latitud: "30.925474",
        longitud: "-116.134011",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000090",
        cluesimb: "BCIMB000080",
        nombre: "RUÍZ Y 14",
        municipio: "ENSENADA",
        localidad: "ENSENADA",
        jurisdiccion: "ENSENADA",
        direccion: "CALLE 14 ENTRE RUIZ Y GASTELUM, Esquina ruiz y 14",
        latitud: "31.876347",
        longitud: "-116.620663",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001181",
        cluesimb: "BCIMB000961",
        nombre: "SALVATIERRA (FLORES MAGÓN)",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "LEY FEDERAL DEL TRABAJO Y OBRERISTAS",
        latitud: "32.483141",
        longitud: "-117.077807",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000312",
        cluesimb: "BCIMB000285",
        nombre: "SAN ANTONIO DE LAS MINAS",
        municipio: "ENSENADA",
        localidad: "VILLA DE JUAREZ (SAN ANTONIO DE LAS MINAS)",
        jurisdiccion: "ENSENADA",
        direccion: "GUILLERMO PRIETO NO. 213",
        latitud: "31.966977",
        longitud: "-116.6519",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000242",
        cluesimb: "BCIMB000220",
        nombre: "SAN VICENTE",
        municipio: "ENSENADA",
        localidad: "SAN VICENTE",
        jurisdiccion: "ENSENADA",
        direccion: "AVE. NIÑOS HÉROES S/N",
        latitud: "31.327672",
        longitud: "-116.247211",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001222",
        cluesimb: "BCIMB001002",
        nombre: "SÁNCHEZ TABOADA",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "CRUZ DEL SUR 226, SÁNCHEZ TABOADA",
        latitud: "32.4678683",
        longitud: "-116.9706684",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA017614",
        cluesimb: "BCIMB001446",
        nombre: "SÁNCHEZ TABOADA REACOMODO",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "CONSTRUCTORES/VIRGO, COL. SANCHEZ TABOADA",
        latitud: "32.461939",
        longitud: "-116.967766",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000773",
        cluesimb: "BCIMB000635",
        nombre: "SANTA ISABEL",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "CALLE DEL SOL Y LA LUNA S/N",
        latitud: "32.6298608",
        longitud: "-115.5756665",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000785",
        cluesimb: "BCIMB000640",
        nombre: "SONORA",
        municipio: "MEXICALI",
        localidad: "EJIDO SONORA",
        jurisdiccion: "MEXICALI",
        direccion: "AV. 27 DE ENERO S/N, MANZANA 6",
        latitud: "32.288619",
        longitud: "-115.233854",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA017754",
        cluesimb: "BCIMB001521",
        nombre: "TERRAZAS DEL VALLE",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "MANZANA 51 LO 1 S/N ENTRE CALLE SAN RAFAEL, LAS DELICIAS Y SANTA MARIA, COL. TERRAZAS DEL VALLE SEGUNDA SECCIÓN",
        latitud: "32.49136",
        longitud: "-116.825954",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA018285",
        cluesimb: "BCIMB001731",
        nombre: "TIJUANA",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "CONSTITUCION ENTRE 8VA Y 9NA 1641, ZONA CENTRO",
        latitud: "32.527386",
        longitud: "-117.03782",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000720",
        cluesimb: "BCIMB000582",
        nombre: "TOLUCA",
        municipio: "MEXICALI",
        localidad: "EJIDO TOLUCA",
        jurisdiccion: "MEXICALI",
        direccion: "CALLE PRINCIPAL S/N, ENFRENTE DE ESC. PRIMARIA",
        latitud: "32.430134",
        longitud: "-115.08241",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA018092",
        cluesimb: "BCIMB001726",
        nombre: "UNEME DE ONCOLOGÍA",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "CALLE DE LA CLARIDAD S/N, COL. PLUTARCO ELIAS CALLES",
        latitud: "32.6223833",
        longitud: "-115.376862",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "HOSPITALES"
    },
    {
        cluesssa: "BCSSA017981",
        cluesimb: "BCIMB001644",
        nombre: "UNEME ENFERMEDADES CRÓNICAS",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "AVE. JOSÉ VASCONSELOS S/N ESQ. BLV PADRE KINO, ZONA RÍO",
        latitud: "32.5256",
        longitud: "-117.0089",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNEMES"
    },
    {
        cluesssa: "BCSSA017993",
        cluesimb: "BCIMB001656",
        nombre: "UNIDAD DE ESPECIALIDADES MEDICAS (SORID) EX EJIDO RUIZ CORTINES",
        municipio: "ENSENADA",
        localidad: "ENSENADA",
        jurisdiccion: "ENSENADA",
        direccion: "CALLE H Y DEL PARQUE S/N, EX-EJIDO RUIZ CORTINEZ",
        latitud: "31.89651",
        longitud: "-116.592991",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNEMES"
    },
    {
        cluesssa: "BCSSA017853",
        cluesimb: "BCIMB001574",
        nombre: "UNIDAD DE ESPECIALIDADES MEDICAS DE BC ENSENADA (UNEME - CIRUGÍA AMBULATORIA)",
        municipio: "ENSENADA",
        localidad: "ENSENADA",
        jurisdiccion: "ENSENADA",
        direccion: "GASTELUM Y 14 NO. 1340 ZONA CENTRO",
        latitud: "31.8763",
        longitud: "-116.619802",
        estratoUnidad: "URBANO",
        nivelAtencion: "SEGUNDO NIVEL",
        tipoUnidad: "HOSPITALES"
    },
    {
        cluesssa: "BCSSA000271",
        cluesimb: "BCIMB000244",
        nombre: "UNIDAD MÓVIL 1",
        municipio: "SAN QUINTIN",
        localidad: "VICENTE GUERRERO",
        jurisdiccion: "VICENTE GUERRERO",
        direccion: "CALLE FRANCISCO DE BORJA NO. 35",
        latitud: "30.708721",
        longitud: "-115.987797",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA000966",
        cluesimb: "BCIMB000780",
        nombre: "UNIDAD MÓVIL 1",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA000983",
        cluesimb: "BCIMB000804",
        nombre: "UNIDAD MÓVIL 10",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA000995",
        cluesimb: "BCIMB000816",
        nombre: "UNIDAD MÓVIL 11",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001000",
        cluesimb: "BCIMB000821",
        nombre: "UNIDAD MÓVIL 12",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001012",
        cluesimb: "BCIMB000833",
        nombre: "UNIDAD MÓVIL 13",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001485",
        cluesimb: "BCIMB001154",
        nombre: "UNIDAD MÓVIL 14",
        municipio: "TECATE",
        localidad: "TECATE",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001490",
        cluesimb: "BCIMB001166",
        nombre: "UNIDAD MÓVIL 15",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001502",
        cluesimb: "BCIMB001171",
        nombre: "UNIDAD MÓVIL 16",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001514",
        cluesimb: "BCIMB001183",
        nombre: "UNIDAD MÓVIL 17",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001526",
        cluesimb: "BCIMB001195",
        nombre: "UNIDAD MÓVIL 18",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001584",
        cluesimb: "BCIMB001253",
        nombre: "UNIDAD MÓVIL 19",
        municipio: "PLAYAS DE ROSARITO",
        localidad: "PLAYAS DE ROSARITO",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA000925",
        cluesimb: "BCIMB000746",
        nombre: "UNIDAD MÓVIL 2",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001531",
        cluesimb: "BCIMB001200",
        nombre: "UNIDAD MÓVIL 20",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001543",
        cluesimb: "BCIMB001212",
        nombre: "UNIDAD MÓVIL 21",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001555",
        cluesimb: "BCIMB001224",
        nombre: "UNIDAD MÓVIL 22",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001560",
        cluesimb: "BCIMB001236",
        nombre: "UNIDAD MÓVIL 23",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001572",
        cluesimb: "BCIMB001241",
        nombre: "UNIDAD MÓVIL 24",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA000930",
        cluesimb: "BCIMB000751",
        nombre: "UNIDAD MÓVIL 3",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA000476",
        cluesimb: "BCIMB000360",
        nombre: "UNIDAD MÓVIL 3",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "ESQUINA AV. LAZARO CARDENAS Y ARTURO BERNAL",
        latitud: "32.623859",
        longitud: "-115.440302",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001806",
        cluesimb: "BCIMB001376",
        nombre: "UNIDAD MOVIL 32",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "ES LA DIRECCION DONDE RESGUARDAN LA UNIDAD QUE ES LA JURISDICCION",
        latitud: "32.463",
        longitud: "-116.9093",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001811",
        cluesimb: "BCIMB001381",
        nombre: "UNIDAD MOVIL 33",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "N/A",
        latitud: "32.4632",
        longitud: "-116.9093",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001823",
        cluesimb: "BCIMB001393",
        nombre: "UNIDAD MOVIL 34",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "N/A",
        latitud: "32.4632",
        longitud: "-116.9093",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA000942",
        cluesimb: "BCIMB000763",
        nombre: "UNIDAD MÓVIL 4",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA000954",
        cluesimb: "BCIMB000775",
        nombre: "UNIDAD MÓVIL 5",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001444",
        cluesimb: "BCIMB001130",
        nombre: "UNIDAD MÓVIL 5",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "AV. LAZARO CARDENAS Y ARTURO BERNAL",
        latitud: "32.623859",
        longitud: "-115.440302",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA000860",
        cluesimb: "BCIMB000681",
        nombre: "UNIDAD MÓVIL 7",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001473",
        cluesimb: "BCIMB001142",
        nombre: "UNIDAD MÓVIL 8",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "AV. LAZARO CARDENAS Y ARTURO BERNAL",
        latitud: "32.623859",
        longitud: "-115.440302",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA018343",
        cluesimb: "BCIMB001772",
        nombre: "UNIDAD MOVIL 9",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "ESQUINA CON CALLE ARTURO BERNAL ES LA DIRECCION DONDE SE RESGUARDA LA UNIDAD",
        latitud: "32.623859",
        longitud: "-115.440302",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA000044",
        cluesimb: "BCIMB000046",
        nombre: "UNIDAD MÓVIL 9",
        municipio: "ENSENADA",
        localidad: "ENSENADA",
        jurisdiccion: "ENSENADA",
        direccion: "CALLE 14 ENTRE RUIZ Y GASTELUM, Esquina ruiz y 14",
        latitud: "31.876347",
        longitud: "-116.620663",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001333",
        cluesimb: "BCIMB001084",
        nombre: "UNIDAD MÓVIL 9",
        municipio: "PLAYAS DE ROSARITO",
        localidad: "PLAYAS DE ROSARITO",
        jurisdiccion: "TIJUANA",
        direccion: "BLVD. INSURGENTES NO. 19811, ESQ. CON CAMICHIN",
        latitud: "32.4632",
        longitud: "-116.9096",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001415",
        cluesimb: "BCIMB001113",
        nombre: "UNIDAD MÓVIL NO. 1",
        municipio: "ENSENADA",
        localidad: "ENSENADA",
        jurisdiccion: "ENSENADA",
        direccion: "AVE. RUIZ Y CALLE 14 NO. 1380",
        latitud: "31.876347",
        longitud: "-116.620663",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA000283",
        cluesimb: "BCIMB000256",
        nombre: "UNIDAD MÓVIL NO. 2",
        municipio: "SAN QUINTIN",
        localidad: "VICENTE GUERRERO",
        jurisdiccion: "VICENTE GUERRERO",
        direccion: "CALLE FRANCISCO DE BORJA NO. 35",
        latitud: "30.708721",
        longitud: "-115.987797",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001420",
        cluesimb: "BCIMB001125",
        nombre: "UNIDAD MÓVIL NO. 2",
        municipio: "ENSENADA",
        localidad: "ENSENADA",
        jurisdiccion: "ENSENADA",
        direccion: "AVE. RUIZ Y CALLE 14 NO. 1380",
        latitud: "31.876347",
        longitud: "-116.620663",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA000295",
        cluesimb: "BCIMB000261",
        nombre: "UNIDAD MÓVIL NO. 3",
        municipio: "SAN QUINTIN",
        localidad: "VICENTE GUERRERO",
        jurisdiccion: "VICENTE GUERRERO",
        direccion: "CALLE FRANCISCO DE BORJA NO. 35",
        latitud: "30.708721",
        longitud: "-115.987797",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA000300",
        cluesimb: "BCIMB000273",
        nombre: "UNIDAD MÓVIL NO. 4",
        municipio: "SAN QUINTIN",
        localidad: "VICENTE GUERRERO",
        jurisdiccion: "VICENTE GUERRERO",
        direccion: "CALLE FRANCISCO DE BORJA NO. 35",
        latitud: "30.708721",
        longitud: "-115.987797",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA000020",
        cluesimb: "BCIMB000022",
        nombre: "UNIDAD MÓVIL NO. 7",
        municipio: "ENSENADA",
        localidad: "ENSENADA",
        jurisdiccion: "ENSENADA",
        direccion: "CALLE 14 ENTRE RUIZ Y GASTELUM, Esquina ruiz y 14",
        latitud: "31.876347",
        longitud: "-116.620663",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA000032",
        cluesimb: "BCIMB000034",
        nombre: "UNIDAD MÓVIL NO. 8",
        municipio: "ENSENADA",
        localidad: "ENSENADA",
        jurisdiccion: "ENSENADA",
        direccion: "CALLE 14 ENTRE RUIZ Y GASTELUM, Esquina ruiz y 14",
        latitud: "31.876347",
        longitud: "-116.620663",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "UNIDAD MOVIL"
    },
    {
        cluesssa: "BCSSA001666",
        cluesimb: "BCIMB001270",
        nombre: "VALLE DE GUADALUPE",
        municipio: "ENSENADA",
        localidad: "FRANCISCO ZARCO (VALLE DE GUADALUPE)",
        jurisdiccion: "ENSENADA",
        direccion: "KILOMETRO 76 CARRETERA ENSENADA A TECATE",
        latitud: "32.105464",
        longitud: "-116.557301",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000370",
        cluesimb: "BCIMB000314",
        nombre: "VALLE DE LA TRINIDAD",
        municipio: "ENSENADA",
        localidad: "POCITOS (VALLE DE LA TRINIDAD)",
        jurisdiccion: "ENSENADA",
        direccion: "PEDRO TERRAZAS S/N",
        latitud: "31.402612",
        longitud: "-115.737995",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000884",
        cluesimb: "BCIMB000705",
        nombre: "VALLE DE LAS PALMAS",
        municipio: "TECATE",
        localidad: "VALLE DE LAS PALMAS",
        jurisdiccion: "TIJUANA",
        direccion: "MANZANA NO. 23 AV. BENITO JUÁREZ S/N",
        latitud: "32.370171",
        longitud: "-116.619738",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA001251",
        cluesimb: "BCIMB001031",
        nombre: "VALLE VERDE",
        municipio: "TIJUANA",
        localidad: "TIJUANA",
        jurisdiccion: "TIJUANA",
        direccion: "AV. DEL PEÑON S/N",
        latitud: "32.5188985",
        longitud: "-116.8736545",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000843",
        cluesimb: "BCIMB000664",
        nombre: "VERACRUZ DOS",
        municipio: "MEXICALI",
        localidad: "EJIDO VERACRUZ DOS",
        jurisdiccion: "MEXICALI",
        direccion: "FRENTE A LA IGLESIA CATOLICA, CALLE SIN SALIDA",
        latitud: "32.397907",
        longitud: "-115.074533",
        estratoUnidad: "RURAL",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    },
    {
        cluesssa: "BCSSA000522",
        cluesimb: "BCIMB000401",
        nombre: "VICENTE GUERRERO",
        municipio: "MEXICALI",
        localidad: "MEXICALI",
        jurisdiccion: "MEXICALI",
        direccion: "AV. GRAL.JOSÉ MORAN Y AV. MARTIN CABRERA",
        latitud: "32.610863",
        longitud: "-115.507579",
        estratoUnidad: "URBANO",
        nivelAtencion: "PRIMER NIVEL",
        tipoUnidad: "CENTRO DE SALUD"
    }
]